apiVersion: v2
name: velero
version: 1.0.0
description: Velero backup and migration for Kubernetes
dependencies:
  - name: velero
    version: "11.1.1"
    repository: "https://vmware-tanzu.github.io/helm-charts"