# TODO create user and access token
# users:
#   - name: renovate
#     fullName: Renovate
#     email: bot@renovateapp.com
#     tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: k8s-gitops
    owner: ops
    private: false
    migrate:
      source: https://github.com/fullstackjam/k8s-gitops
      mirror: false
