apiVersion: v2
name: rook-ceph
version: 0.0.0
dependencies:
  - name: rook-ceph
    version: v1.19.0
    repository: https://charts.rook.io/release
  - name: rook-ceph-cluster
    version: v1.19.0
    repository: https://charts.rook.io/release
  - name: snapshot-controller
    version: 5.0.2
    repository: https://piraeus.io/helm-charts
