apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  version: 8.19.9
  count: 1
  elasticsearchRefs:
  - name: elasticsearch
    clusterName: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: logstash
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
  services:
  - name: beats
    service:
      spec:
        type: ClusterIP
        ports:
        - port: 5044
          name: beats
          protocol: TCP
          targetPort: 5044
  volumeClaimTemplates:
  - metadata:
      name: logstash-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard-rwo
  config:
    log.level: info
    pipeline.workers: 2
    pipeline.batch.size: 125
    pipeline.batch.delay: 50
    queue.type: persisted
    queue.max_bytes: 1gb
    dead_letter_queue.enable: true
  pipelines:
  - pipeline.id: main
    config.string: |
      input {
        beats {
          port => 5044
        }
      }
      filter {
        if [kubernetes][namespace] {
          mutate {
            add_field => { "[@metadata][index_suffix]" => "%{[kubernetes][namespace]}" }
          }
        } else {
          mutate {
            add_field => { "[@metadata][index_suffix]" => "unknown" }
          }
        }
      }
      output {
        elasticsearch {
          hosts => ["${ELASTICSEARCH_ES_HOSTS}"]
          user => "${ELASTICSEARCH_ES_USER}"
          password => "${ELASTICSEARCH_ES_PASSWORD}"
          ssl_certificate_authorities => ["${ELASTICSEARCH_ES_SSL_CERTIFICATE_AUTHORITY}"]
          index => "filebeat-%{[@metadata][index_suffix]}-%{+YYYY.MM.dd}"
        }
      }
